pleins de trucs
WildCodeSchool/orleans-0217-numo pull request #75
Opened 2017-07-18 14:49 UTC by Fanny-Jan

2017-07-18 15:33 UTC, sblondeau requested changes

2017-07-18 15:33 UTC, sblondeau commented on app/Resources/views/company/show.html.twig
> +    <a href="{{ path('company_edit', { 'id': 1 }) }}"><button type="button" value="MODIFIER">MODIFIER</button></a>
pas mettre le 1 en dur mais company.id

2017-07-18 15:39 UTC, sblondeau approved these changes

2017-07-18 15:39 UTC, merged

2017-07-24 12:06 UTC, Fanny-Jan commented
![](https://github.trello.services/images/mini-trello-icon.png) [validateurs yml fosuser](https://trello.com/c/JquLCi4N/13-validateurs-yml-fosuser)