Admin ajout upload de pdf + image
WildCodeSchool/orleans-0217-numo pull request #9
Opened 2017-06-27 12:13 UTC by SarahOmayra

2017-06-27 14:05 UTC, sblondeau requested changes

2017-06-27 14:05 UTC, sblondeau commented on app/Resources/FOSUserBundle/views/Profile/edit.html.twig
> +    <script src="{{ asset('http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.4/summernote.js') }}"></script>
y a 2 summernote, le cdn à effacer

2017-06-27 14:05 UTC, sblondeau commented on app/Resources/views/base.html.twig
> +            <link rel="stylesheet" href="{{ asset('css/style.css') }}">
le style.css en dernier

2017-06-27 14:05 UTC, sblondeau commented on app/Resources/views/layoutAdmin.html.twig
> +                2017 © NUM'O - Site Web créé par la Wild Code School Orléans
si vous avez le meme footer dans les deux, il faut soit qu'il soit dans le base.html, soit include un meme fichier footer

2017-06-27 14:05 UTC, sblondeau commented on src/NumoBundle/Form/CompanyType.php
> +                'label' => 'Contenu',
C'est clair d'avoir deux fois le label titre et contenu ?

2017-06-27 14:05 UTC, sblondeau commented on web/css/style.css
> +<<<<<<< HEAD
un reste de merge mal corrigé

2017-06-27 22:17 UTC, sblondeau requested changes

2017-06-27 22:17 UTC, sblondeau commented on app/Resources/views/company/edit.html.twig
> +    {{ form_label(edit_form.contactEmail) }}
ne pas hésiter à faire de retours à la ligne entre chaque élément de form, pour plus de lisibilité du code!

2017-06-27 22:17 UTC, sblondeau commented on app/Resources/views/company/index.html.twig
> +{#
pas de code commenté dans une PR

2017-06-27 22:17 UTC, sblondeau commented on app/Resources/views/userpromote/index.html.twig
>          <a href="{{ path('pagecontent_new') }}"><button type="button" value="CREATION DE CONTENU">+</button></a>
code commenté

2017-06-27 22:17 UTC, sblondeau commented on app/Resources/views/userpromote/index.html.twig
>          <br/>
pas de br!

2017-06-27 22:17 UTC, sblondeau commented on app/Resources/views/userpromote/index.html.twig
>                      <td class="admin">{{ user.roles.0 }}</td>
il ne faut pas recréer un table entre le thead et le tbody
c'est <table>
<thead> ... </thead>
<tbody> ... </tbody>
</table>

2017-06-28 08:37 UTC, open-it approved these changes

2017-06-28 08:38 UTC, merged